# This Makefile is only for testing. C callers should follow the instructions
# in ./README.md to incorporate these C files into their existing build.

NAME=blake3
CC=gcc
CFLAGS=-O3 -Wall -Wextra -std=c11 -pedantic -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIE -fvisibility=hidden
LDFLAGS=-pie -Wl,-z,relro,-z,now
TARGETS=
ASM_TARGETS=
EXTRAFLAGS=-Wa,--noexecstack

UNAME_S := $(shell uname -s)
UNAME_M := $(shell uname -m)

RMR_OS_WINDOWS=
RMR_OS_DARWIN=
RMR_OS_LINUX=
RMR_OS_FREEBSD=
RMR_OS_OPENBSD=
RMR_OS_NETBSD=

ifneq (,$(filter MINGW% MSYS% CYGWIN%,$(UNAME_S)))
  RMR_OS_WINDOWS=1
else ifeq ($(UNAME_S),Darwin)
  RMR_OS_DARWIN=1
else ifeq ($(UNAME_S),Linux)
  RMR_OS_LINUX=1
else ifeq ($(UNAME_S),FreeBSD)
  RMR_OS_FREEBSD=1
else ifeq ($(UNAME_S),OpenBSD)
  RMR_OS_OPENBSD=1
else ifeq ($(UNAME_S),NetBSD)
  RMR_OS_NETBSD=1
endif

RMR_ARCH_X86_64=
RMR_ARCH_X86_32=
RMR_ARCH_AARCH64=
RMR_ARCH_ARM=

ifneq (,$(filter x86_64 amd64,$(UNAME_M)))
  RMR_ARCH_X86_64=1
else ifneq (,$(filter i386 i486 i586 i686,$(UNAME_M)))
  RMR_ARCH_X86_32=1
else ifneq (,$(filter aarch64 arm64,$(UNAME_M)))
  RMR_ARCH_AARCH64=1
else ifneq (,$(filter armv6% armv7% armv8% arm,$(UNAME_M)))
  RMR_ARCH_ARM=1
endif

ifeq ($(RMR_ARCH_X86_64)$(RMR_ARCH_X86_32),)
  EXTRAFLAGS += -DBLAKE3_NO_SSE2 -DBLAKE3_NO_SSE41 -DBLAKE3_NO_AVX2 -DBLAKE3_NO_AVX512
endif

ifneq ($(RMR_OS_WINDOWS),)
  EXTRAFLAGS += -DRMR_OS_WINDOWS=1
endif
ifneq ($(RMR_OS_DARWIN),)
  EXTRAFLAGS += -DRMR_OS_DARWIN=1
endif
ifneq ($(RMR_OS_LINUX),)
  EXTRAFLAGS += -DRMR_OS_LINUX=1
endif
ifneq ($(RMR_OS_FREEBSD),)
  EXTRAFLAGS += -DRMR_OS_FREEBSD=1
endif
ifneq ($(RMR_OS_OPENBSD),)
  EXTRAFLAGS += -DRMR_OS_OPENBSD=1
endif
ifneq ($(RMR_OS_NETBSD),)
  EXTRAFLAGS += -DRMR_OS_NETBSD=1
endif
ifneq ($(RMR_ARCH_X86_64),)
  EXTRAFLAGS += -DRMR_ARCH_X86_64=1
endif
ifneq ($(RMR_ARCH_X86_32),)
  EXTRAFLAGS += -DRMR_ARCH_X86_32=1
endif
ifneq ($(RMR_ARCH_AARCH64),)
  EXTRAFLAGS += -DRMR_ARCH_AARCH64=1
endif
ifneq ($(RMR_ARCH_ARM),)
  EXTRAFLAGS += -DRMR_ARCH_ARM=1
endif

ifdef BLAKE3_NO_SSE2
EXTRAFLAGS += -DBLAKE3_NO_SSE2
else
TARGETS += blake3_sse2.o
ifneq ($(RMR_ARCH_X86_64),)
  ifneq ($(RMR_OS_WINDOWS),)
    ASM_TARGETS += blake3_sse2_x86-64_windows_gnu.S
  else
    ASM_TARGETS += blake3_sse2_x86-64_unix.S
  endif
endif
endif

ifdef BLAKE3_NO_SSE41
EXTRAFLAGS += -DBLAKE3_NO_SSE41
else
TARGETS += blake3_sse41.o
ifneq ($(RMR_ARCH_X86_64),)
  ifneq ($(RMR_OS_WINDOWS),)
    ASM_TARGETS += blake3_sse41_x86-64_windows_gnu.S
  else
    ASM_TARGETS += blake3_sse41_x86-64_unix.S
  endif
endif
endif

ifdef BLAKE3_NO_AVX2
EXTRAFLAGS += -DBLAKE3_NO_AVX2
else
TARGETS += blake3_avx2.o
ifneq ($(RMR_ARCH_X86_64),)
  ifneq ($(RMR_OS_WINDOWS),)
    ASM_TARGETS += blake3_avx2_x86-64_windows_gnu.S
  else
    ASM_TARGETS += blake3_avx2_x86-64_unix.S
  endif
endif
endif

ifdef BLAKE3_NO_AVX512
EXTRAFLAGS += -DBLAKE3_NO_AVX512
else
TARGETS += blake3_avx512.o
ifneq ($(RMR_ARCH_X86_64),)
  ifneq ($(RMR_OS_WINDOWS),)
    ASM_TARGETS += blake3_avx512_x86-64_windows_gnu.S
  else
    ASM_TARGETS += blake3_avx512_x86-64_unix.S
  endif
endif
endif

ifdef BLAKE3_USE_NEON
EXTRAFLAGS += -DBLAKE3_USE_NEON=1
TARGETS += blake3_neon.o
endif

ifdef BLAKE3_NO_NEON
EXTRAFLAGS += -DBLAKE3_USE_NEON=0
endif

all: blake3.c blake3_dispatch.c blake3_portable.c main.c $(TARGETS)
	$(CC) $(CFLAGS) $(EXTRAFLAGS) $^ -o $(NAME) $(LDFLAGS)

blake3_sse2.o: blake3_sse2.c
	$(CC) $(CFLAGS) $(EXTRAFLAGS) -c $^ -o $@ -msse2

blake3_sse41.o: blake3_sse41.c
	$(CC) $(CFLAGS) $(EXTRAFLAGS) -c $^ -o $@ -msse4.1

blake3_avx2.o: blake3_avx2.c
	$(CC) $(CFLAGS) $(EXTRAFLAGS) -c $^ -o $@ -mavx2

blake3_avx512.o: blake3_avx512.c
	$(CC) $(CFLAGS) $(EXTRAFLAGS) -c $^ -o $@ -mavx512f -mavx512vl

blake3_neon.o: blake3_neon.c
	$(CC) $(CFLAGS) $(EXTRAFLAGS) -c $^ -o $@

test: CFLAGS += -DBLAKE3_TESTING -fsanitize=address,undefined
test: all
	./test.py

asm: blake3.c blake3_dispatch.c blake3_portable.c main.c $(ASM_TARGETS)
	$(CC) $(CFLAGS) $(EXTRAFLAGS) $^ -o $(NAME) $(LDFLAGS)

test_asm: CFLAGS += -DBLAKE3_TESTING -fsanitize=address,undefined 
test_asm: asm
	./test.py

example: example.c blake3.c blake3_dispatch.c blake3_portable.c $(ASM_TARGETS)
	$(CC) $(CFLAGS) $(EXTRAFLAGS) $^ -o $@ $(LDFLAGS)

clean: 
	rm -f $(NAME) *.o
