[alias]
rmr-freestanding = "build --lib --no-default-features --features pure"
rmr-baremetal = "build --lib --no-default-features --features pure --target thumbv7em-none-eabi"
rmr-baremetal-m = "build --lib --no-default-features --features pure --target thumbv7em-none-eabi"
rmr-baremetal-a32 = "build --lib --no-default-features --features pure --target armv7a-none-eabi"
rmr-baremetal-a64 = "build --lib --no-default-features --features pure --target aarch64-unknown-none"

[target.wasm32-wasip1]
runner = "wasmtime"
