name: publish_b3sum_binaries

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  BLAKE3_CI: "1"
  RUSTFLAGS: "-D warnings"

jobs:
  cargo_tests:
    name: ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target: [
          { "os": "ubuntu-24.04",  "rust-target": "x86_64-unknown-linux-musl", "name": "Linux" },
          { "os": "macos-26",   "rust-target": "x86_64-apple-darwin",       "name": "macOS" },
          { "os": "windows-2025-vs2026", "rust-target": "x86_64-pc-windows-msvc",    "name": "Windows" },
        ]

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: "3.x"
      - run: pip install PyGithub==2.10.0
      - run: sudo apt-get install musl-tools
        if: matrix.target.os == 'ubuntu-24.04'
      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable ref observed 2026-09-27
        with:
          targets: ${{ matrix.target.rust-target }}
      - name: build b3sum
        id: build_b3sum
        run: python -u .github/workflows/build_b3sum.py ${{ matrix.target.rust-target }}
      - name: upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TAG: ${{ github.ref }}
        run: python -u .github/workflows/upload_github_release_asset.py ${{ steps.build_b3sum.outputs.bin_path }}
